### PR TITLE
add authentication to pages

### LINKED ISSUE #10: [New] Phone Number - OTP Authentication Modal

### LINKED ISSUE #17: [IMPROVEMENT] Fix routes
Remove '/admin' route.

### PR DESCRIPTION
**Pull request by catrawalkar**
Closes #10

### CODE REVIEW

**Comment by RonLek** [comment]
@catrawalkar there seem to be a few conflicts. Could you please resolve them?

**Comment by catrawalkar** [comment]
Solves #17

**Comment by RonLek** [comment]
@catrawalkar can you please add client setup steps (where and how to get the env variables, creating a copy of `.env.sample` as `.env` and starting up the client) in the README.md. It'll really help in getting started. Thanks.

**Review by RonLek — APPROVED** [review]
LGTM!

**Comment by RonLek** [comment]
@catrawalkar there seem to be a few conflicts. Feel free to merge after resolving. PR LGTM!

**Pull request merged**
